### ISSUE TITLE
点击课程详细信息有时候还是会闪退

### ISSUE THREAD

**Issue by xiaofud** [daidaijie/SyllabusApplication#3]
RT, 同步可以解决该问题...早点修复这个BUG吧

**Comment by daidaijie** [comment]
同步后还会这样吗

**Comment by xiaofud** [comment]
同步之后只是短暂解决问题.
另外经过测试, 闪退现象大概是这样的, 有效和闪退间断发生...同步后依然如此, 第一次是闪退, 第二次就正常, 然后又会闪退...

**Comment by daidaijie** [comment]
@xiaofud 已修复，已验证
